<template>
  <div class="privacy-policy">
    <h1>Privacy Policy</h1>
    <p>Thank you for your interest in our website. Protecting your privacy is very important to us. Below, we inform you in detail about how we handle your data.</p>

    <h2>Collection, Processing, and Use of Personal Data</h2>
    <p>You can visit our site without providing any personal information. We only store access data without personal reference, such as the name of your Internet service provider, the page from which you visited us, or the name of the requested file. This data is used solely to improve our offering and does not allow any inference to your person.</p>

    <h2>Use of Matomo (formerly Piwik)</h2>
    <p>This website uses Matomo, an open-source software for statistical analysis of visitor access. Matomo uses "cookies", which are text files stored on your computer that allow an analysis of your use of the website. The information generated by the cookie about your use of this website is stored on our server. The IP address is anonymized immediately after processing and before storage.</p>
    
    <p>You can prevent the installation of cookies by adjusting your browser software accordingly; however, we point out that in this case, you may not be able to fully use all the functions of this website.</p>

    <h2>Objection to Data Collection</h2>
    <p>If you do not agree with the storage and use of your data, you can disable the storage and use here. In this case, an opt-out cookie will be stored in your browser that prevents Matomo from saving usage data. If you delete your cookies, this will result in the Matomo opt-out cookie also being deleted. The opt-out must be reactivated when you visit our site again.</p>

    <p>More information about Matomo can be found at <a href="https://matomo.org/privacy-policy/" target="_blank">https://matomo.org/privacy-policy/</a>.</p>
  </div>
</template>

<script>
export default {
  name: 'PrivacyPolicy'
}
</script>

<style scoped>
.privacy-policy {
  max-width: 800px;
  margin: auto;
  padding: 20px;
  font-family: Arial, sans-serif;
  line-height: 1.6;
}
.privacy-policy h1 {
  color: #333;
}
.privacy-policy a {
  color: #1a0dab;
}
</style>
